# Generated by Django 3.2.6 on 2021-08-17 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.categories'),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='products',
            name='product_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
